management:
  endpoints:
    web:
      exposure:
        include: "info"

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:devDB
    user: sa
    password:

server:
  port: 8081